[webservers]
web-1   ansible_host=93.77.185.79 fqdn=fhm1iibjk6uqdjhs9epp.auto.internal
web-2   ansible_host=111.88.246.188 fqdn=fhmqh6cco3dgmjk8luv2.auto.internal

[databases]
db-main   ansible_host=84.201.134.114 fqdn=fhm8trfujkdassfmprq7.auto.internal
db-replica   ansible_host=84.201.159.252 fqdn=fhmefa98giqu6hugouo1.auto.internal

[storage]
storage   ansible_host=111.88.246.143 fqdn=fhmae9tgfankitl7dcja.auto.internal
